scheduler/api/routes.py
from scheduler import db, utils
from scheduler.api.aggr_utils import *
from scheduler.api import auth
from flask import Blueprint, jsonify, request, abort, escape, redirect
from bson.objectid import ObjectId
from bson.int64 import Int64
from ast import literal_eval
import re
import datetime

api = Blueprint('api', __name__)
"""
При регистрации поля логин и пароль должны удовлетворять всем критериям
Username:
1. min length = 3
2. a-z0-9_.-
3. only one _ . - in a row
4. username must not be already taken
Password:
- min length = 6
При создании новоого расписания его поля должны удовлетворять всем критериям
Schedule_Name:
1. min length = 3
Alias:
1. min length = 3
2. A-Za-z0-9_.-
3. only one _ or - in a row
4. alias must not be already taken
"""

MIN_USERNAME_LENGTH = 5
MIN_PASSWORD_LENGTH = 6

MIN_NAME_LENGTH = 3
MIN_ALIAS_LENGTH = 3
USERNAME_MATCH_REGEX = '[a-z0-9_.-]+'
ALIAS_MATCH_REGEX = '[A-Za-z0-9_.-]+'
WRONG_CREDENTIALS = 'wrong_credentials'

def get_args():
    result = {}
    for key, value in request.args.items():
        result[key] = value
    for key, value in request.form.items():
        if key not in result:
            result[key] = value
    return result


@api.route('/api/authenticate', methods=['POST'])
def authorization():
    print(f"authorization = {get_args()}")
    username = escape(get_args()['username']).lower()
    password = get_args()['password']
    user = db.users.find_one({'username': username})
    if user is None:
        return json_error(WRONG_CREDENTIALS)

    salt = user['salt']
    if not auth.check_password(password, salt, user["password"]):
        return json_error(WRONG_CREDENTIALS)
    user_id = str(user['_id'])


    if 'firebase_id' in get_args():
        firebase_id = get_args()['firebase_id']
        db.users.update_one({'_id': ObjectId(user_id)}, {'$set': {'firebase_id': firebase_id}})


    print(f"authorization: id = {user_id} token = {auth.gen_signed_token(user_id)}")
    return json_success(data={'token': auth.gen_signed_token(user_id)}), 200



@api.route("/api/users_self", methods=["GET"])
@auth.authenticate()
def get_user_self(user=None):
    if not user:
        return json_error("not authorized"), 200
    print(f"get_user_self = {user}")
    return manage_single_user(username=user["username"])


@api.route('/api/users/', methods=['GET', 'POST'])
@auth.authenticate()
def manage_users(user=None):
    if request.method == 'GET':
        match_fields = {}
        return_fields = None
        limit_int = None
        skip_int = None
        whitelist_match_keys = ['username', '_id']
        whitelist_return_fields = ['_id', 'username', 'schedules']

        current_field = ''
        try:
            current_field = 'match_fields'
            if 'match_fields' in request.args:
                match_fields = literal_eval(request.args['match_fields'])
            current_field = 'return_fields'
            if 'return_fields' in request.args:
                return_fields = literal_eval(request.args['return_fields'])
            current_field = 'limit'
            if 'limit' in request.args:
                limit_int = int(request.args['limit'])
            current_field = 'skip'
            if 'skip' in request.args:
                skip_int = int(request.args['skip'])
        except:
            return json_error(type='field', field=current_field)

        match_fields = whitelist_arr(whitelist_match_keys, match_fields)
        match = parse_match_stage(match_fields, get_regex_wrapper('.*', '.*'))

        aggregation = get_basic_user_aggregation()
        aggregation.append({'$match': match})
        result_obj = db.users.aggregate(aggregation)
        aggregated_result = []
        for item in result_obj:
            aggregated_result.append(item)

        if skip_int is not None:
            aggregated_result = skip(skip_int, aggregated_result)
        if limit_int is not None:
            aggregated_result = limit(limit_int, aggregated_result)

        if return_fields:
            return_fields = whitelist_arr(whitelist_return_fields, return_fields)
            aggregated_result = [whitelist_arr(return_fields, item) for item in aggregated_result]

        for found_user in aggregated_result:
            if 'schedules' not in found_user:
                break
            found_user['schedules'] = return_only_visible(user=user, schedules=found_user['schedules'])

        return json_success(objectid_to_str(aggregated_result))
    elif request.method == 'POST':
        username = escape(request.args['username']).lower()
        password = request.args['password']

        result = verify_username(username)
        if result is not None:
            return result
        result = verify_password(password)
        if result is not None:
            return result

        firebase_id = ''
        if 'firebase_id' in request.args:
            firebase_id = request.args['firebase_id']

        salt = auth.gen_salt()
        salted_password = auth.hash_password_and_salt(password, salt)
        inserted_user = db.users.insert_one({
            'username': username,
            'password': salted_password,
            'salt': salt,
            'firebase_id': firebase_id
        })
        user_id = str(inserted_user.inserted_id)
        return json_success(data={'token': auth.gen_signed_token(user_id)}), 201


@api.route('/api/users/<username>', methods=['GET', 'PATCH'])
@auth.authenticate()
def manage_single_user(username, user=None):
    username = username.lower()
    if request.method == 'GET':
        return_fields = None
        #whitelist_return_fields = ['_id', 'username', 'schedules']

        if 'return_fields' in get_args():
            try:
                return_fields = literal_eval(get_args()['return_fields'])
                #return_fields = whitelist_arr(whitelist_return_fields, return_fields)
            except:
                return json_error(type='field', field='return_fields')

        aggregation = get_basic_user_aggregation()
        aggregation.append({'$match': {'username': username}})
        result_obj = db.users.aggregate(aggregation)
        found_user = None
        for item in result_obj:
            found_user = item

        if not found_user:
            return json_error('not found'), 200

        if return_fields:
            found_user = whitelist_arr(return_fields, found_user)

        if 'schedules' in found_user:
            found_user['schedules'] = return_only_visible(user=user, schedules=found_user['schedules'])
        
        return json_success(objectid_to_str(found_user))

    elif request.method == 'PATCH':
        if not user or username != user['username']:
            return json_error('not authorized'), 200
        user = db.users.find_one({'_id': user["_id"]})
        username = user['username']
        password = user['password']
        if 'username' in get_args():
            username = get_args()['username']
            verify_username(username)


        print("patching user")
        if 'auth_password' in get_args() and 'password' in get_args():
            print("changing password")
            auth_password = auth.hash_password_and_salt(get_args()['auth_password'], salt=user['salt'])
            new_password = get_args()['password']
            if verify_password(new_password) is not None:
                return verify_password(new_password)

            if auth_password != password:
                return json_error('field', field='auth_password'), 200
            print(f'new password = {new_password}')
            password = auth.hash_password_and_salt(new_password, salt=user['salt'])
        db.users.update_one({'_id': user['_id']}, {'$set':{
            'username': username,
            'password': password
        }})
        return json_success(), 200
    elif request.method == 'DELETE':
        if not user or username != user['username']:
            return json_error('not authorized'), 200
        db.users.remove_one({'_id': user['_id']})
        return json_success(), 200


@api.route('/api/schedules/', methods=['GET', 'POST'])
@auth.authenticate()
def manage_schedules(user=None):
    if request.method == 'GET':
        match_fields = {}
        return_fields = None
        limit_int = None
        skip_int = None

        current_field = ''
        try:
            current_field = 'match_fields'
            if 'match_fields' in get_args():
                match_fields = literal_eval(get_args()['match_fields'])
                print(match_fields)
            current_field = 'return_fields'
            if 'return_fields' in get_args():
                return_fields = literal_eval(get_args()['return_fields'])
            current_field = 'limit'
            if 'limit' in get_args():
                limit_int = int(get_args()['limit'])
            current_field = 'skip'
            if 'skip' in get_args():
                skip_int = int(get_args()['skip'])
        except:
            return json_error(type='field', field=current_field), 200

        match = parse_match_stage(match_fields, get_regex_wrapper(pre='.*', post='.*'))
        aggregation = get_basic_schedule_aggregation()
        aggregation.append({'$match': match})
        print(match)
        result_obj = db.schedules.aggregate(aggregation)

        aggregated_result = []
        for item in result_obj:
            print(item)
            aggregated_result.append(item)

        shown_schedules = return_only_visible(user=user, schedules=aggregated_result)

        if return_fields is not None:
            shown_schedules = [whitelist_arr(return_fields, item) for item in shown_schedules]

        if skip_int is not None:
            shown_schedules = skip(skip_int, shown_schedules)
        if limit_int is not None:
            shown_schedules = limit(limit_int, shown_schedules)
        return json_success(objectid_to_str(shown_schedules))
    elif request.method == 'POST':
        if not user:

scheduler/templates/create_schedule.html
{% extends 'default_layout.html' %}
{% block head %}
    {{ super() }}
    <style>
        .dayholder{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(185px, 1fr));
        }
        .card {
            border: 0px;
            border-radius: 0px;
        }
        .card-body .form-control{
            border-radius: 0px
        }
        .nav-tabs .nav-item {
            display: inline-block;
        }
        .nav-tabs .nav-item card-header active {
            background-color: f3f3f3;
        }
    </style>
    <script>
    $(function readyFn(){
        $('#schedule_name').keyup(check_name)
        $('#alias').change(check_alias)
        $('#first_day').keyup(check_first_date)

        function check_button(){
            if ($('#schedule_name').hasClass('is-valid') && $('#alias').hasClass('is-valid')){
                if ($('#week_count').val()>0){
                    if ($('#first_day').hasClass('is-valid')){
                        return true
                    }else{
                        return false
                    }
                }
                return true
            }
            return false
        }

        function check_name(){
            var name = $('#schedule_name').val()
            if (name.length > 0){
                check_alias()
                $('#schedule_name').addClass('is-valid').removeClass('is-invalid')
            } else {
                $('#done').attr('disabled', true)
                $('#schedule_name').addClass('is-invalid').removeClass('is-valid')
            }
            $('#done').attr('disabled', !check_button())
        }
        function check_alias(){
            var alias = $('#alias').val()
            if (alias.length > 0){
                if (!/^[A-Za-z0-9-_]+$/.test(alias)){
                    $('#alias-feedback').empty().append('Используйте лишь символы латиницы (A-z), цифры (0-9), тире "-" и подчёркивание "_"')
                    $('#alias').addClass('is-invalid').removeClass('is-valid')
                }
                $.get('/api/schedules/'+alias)
                    .done(function(){
                        $('#alias').addClass('is-invalid').removeClass('is-valid')
                    })
                    .fail(function(result){
                        var name = $('#schedule_name').val()
                        if (result.status == 404){ 
                            $('#alias').addClass('is-valid').removeClass('is-invalid')
                        }
                    })
            }
            $('#alias').addClass('is-valid').removeClass('is-invalid')
            $('#done').attr('disabled', !check_button())
        }

        function check_first_date (){
            var date = $('#first_day').val()
            if ( (date.length >= 3 && date[2] != ".") || (date.length >= 6 && date[5] != '.')){
                $('#first_day').addClass('is-invalid').removeClass('is-valid')
            }
            if (/[\d]{2}\.[\d]{2}\.[\d]{2}/.test(date)){
                $('#first_day').addClass('is-valid').removeClass('is-invalid')
            }
            $('#done').attr('disabled', !check_button())
        }

        $('#week_count').change(function(){
            var week_count = $('#week_count').val()
            $('.nav-item').removeClass('active show')
            $('#nav-week-1').tab('show')
            if (week_count > 0) {
                $('#first_day_container').removeAttr('hidden')
                $('.weektabholder').removeAttr('hidden')
            } else {
                $('#first_day_container').attr('hidden', '')
                $('.weektabholder').attr('hidden', '')
            }
            for (var i=0; i<5; i++){
                $('#nav-week-'+(i+1)).attr('hidden', !(i<=week_count))
            }
            $('#done').attr('disabled', !check_button())
        })

        $('#done').click(function(){
            var schedule_name = $('#schedule_name').val()
            var alias = $('#alias').val()
            var availability = $('#availability').val()
            var week_count = $('#week_count').val()
            var first_day = $('#first_day').val()
            var schedule = [];
            
            for (var w=0; w<week_count+1; w++){
                var week = [];
                if (w <= week_count ){
                    for (var d=0; d<7; d++){
                        var day = [];
                        for (var l=0; l<9; l++){
                            day.push($(`#lesson-${w}-${d}-${l}`).val())
                        }
                        week.push(day)
                    }
                } else {
                    break;
                }
                schedule.push(week)
            }
            $.post('{{url_for('create_schedule')}}', {
                'schedule_name':schedule_name,
                'alias':alias,
                'availability':availability,
                'first_day':first_day,
                'schedule': JSON.stringify(schedule)}).done(function(result){
                    if (result.status == 201){
                        window.location.replace("{{url_for('home')}}")
                    }
                });
        })
    })
    </script>
{% endblock %}
{% block content %}
    <div class="card bg-light shadow-sm mb-2">
        <div class="card-header d-flex justify-content-between align-items-center">
            <b>Настройки Расписания</b>
            <button class="btn btn-primary" id="done" disabled>Создать</button>
        </div>
        <div class="card-body">
            <div class="row no-gutters mb-2">
                <div class="input-group input-group-sm col-md mb-2 mb-md-0 mr-md-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Название</span>
                    </div>
                    <input class="form-control" name="schedule_name" id="schedule_name" type="text" placeholder='Например "группа 406"'>
                </div>
                <div class="input-group input-group-sm col-md">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Ссылка</span>
                    </div>
                    <input class="form-control" name="alias" id="alias" type="text" placeholder='group-406'>
                    <div class="invalid-feedback" id="alias-feedback">Данная ссылка занята, выберите другую или оставьте поле пустым, тогда ссылка выберется автоматически</div>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-md input-group input-group-sm mb-2 mb-md-0 mr-md-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Доступность</span>
                    </div>
                    <select class="form-control" name="availability" id="availability">
                        <option value="public">Публичное</option>
                        <option value="private">Приватное</option>
                    </select>
                </div>
                <div class="col-md input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Кол-во недель</span>
                    </div>
                    <select class="form-control" name="week_count" id="week_count">
                        <option value="0">Одна</option>
                        <option value="1">Две</option>
                        <option value="2">Три</option>
                        <option value="3">Четыре</option>
                        <option value="4">Пять</option>
                    </select>
                </div>
            </div>
            <div class="row no-gutters mt-2" id="first_day_container" hidden>
                <div class="col-md input-group input-group-sm">
                    <div class="input-group-prepend">
                        <p class="input-group-text">Дата начала учёбы</p>
                    </div>
                    <input class="form-control" name="first_day" id="first_day" type="text" maxlength="8" placeholder='Например 01.09.18'>
                    <div class="invalid-feedback">Введите дату начала вашей первой недели обучения в формате дд.мм.гг</div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block no_container %}
    {% set weekdays=['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'] %}
    <div class="container-fluid px-0 px-lg-5">
        <div class="weekholder">
            <nav class="weektabholder" hidden>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                {% for i in range(5) %}
                    <a class="nav-item nav-link p-2 px-3 mr-1 {% if i==0 %}active{%endif%}" id="nav-week-{{i+1}}" data-toggle="tab" href="#week-{{i+1}}" >
                        <h6 class="mb-0">{{i+1}}-я</h6>
                    </a>
                {% endfor %}
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
            {% for w in range(5) %}
                <div class="tab-pane fade show {% if w<1 %}active{%endif%}" id="week-{{w+1}}">
                    <div class="dayholder" >
                    {% for i in range(7) %}
                        <div class="shadow-sm">
                            <div class="card-header pb-1 text-center"><h6>{{weekdays[i]}}</h6></div>
                            <div class="card-body p-0">
                                {% for j in range(9) %}<input class="form-control form-control-sm" id="lesson-{{w}}-{{i}}-{{j}}" style="" type="text" placeholder="{{j+1}}">{% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock no_container %}

scheduler/templates/home.html
{% extends 'default_layout.html' %}
{% block content %}
    {% if user %}
        {% for schedule in schedules %}
            {% import 'macros.html' as macros %}
            {{ macros.schedule(user=user, schedule=schedule)}}
        {% else %}
            <div class="rounded border shadow-sm bg-light mb-3" style="border: 0px">
                <div class="card-header rounded pb-1"><h5>Ой, вы не подписаны ни на одно расписание</h5></div>
                <div class="card-body">
                    <p class="mb-0">&emsp;Вы можете создать своё расписание или найти уже созданное воспользовавшись поиском. Когда у вас появятся расписания они будут отображатся тут :)</p>
                </div>
            </div>
        {% endfor %}
        <div class="d-flex flex-row">
            <a class="btn btn-sm btn-outline-primary p-2 rounded-pill mx-auto" href="{{url_for('web.create_schedule')}}">Создать новое расписание</a>
        </div>
    {% else %}
        {% import 'macros.html' as macros %}
        {{ macros.message(title='Добро пожаловать!', messages=[
            'Вы не авторизованы, поэтому сейчас вы можете лишь находить и просматривать расаписания.',
            'Авторизуйтесь чтобы получить возможность создавать свои и подписываться на расписания, созданные другими пользователями.']) }}
    {% endif %}
    <!--div class="message rounded">
        <a class="message-title rounded" href="{{url_for('static', filename='css/main.css')}}">Обновить main.css</a>
    </div>
    <div class="message rounded">
        <a class="message-title rounded" href="{{url_for('static', filename='bootstrap-4.2.1/css/bootstrap.css')}}">Обновить bootstrap.css</a>
    </div-->
{% endblock content %}
{% block no_container%}{% endblock %}

scheduler/templates/login.html
{% extends 'default_layout.html' %}
{% block head %}
    {{super()}}
    <style>
        html, body {
            height: 100%;
        }
        body{
            display: flex;
            align-items: center;
            justify-content: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f8f8f8;
        }
        form {
            width: 100%;
            max-width: 380px;
            min-width: 300px;
        }
        .form-control {
            position: relative;
            font-size: 20px;
            height: auto;
        }
        .form-control:focus {
            z-index: 2;
        }
        .btn {
            position: relative;
            font-size: 18px;
        }
    </style>
    <script>
    $(function readyFn(){
        $('#username_input, #password_input').keyup(function(){
            var username = $('#username_input').val();
            var password = $('#password_input').val();
            $('#done').attr('disabled', !(username.length > 0 && password.length > 0));
        });
    });
    </script>
{% endblock %}
{% block navbar %}{% endblock %}
{% block container %}{% endblock %}
{% block no_container %}
    <form class="form px-3" action="" method="post">
        <h2 class="mb-3">Вход</h2>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{category}} rounded">{{message}}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="rounded-group-vertical mb-2">
            <input class="form-control rounded" type="text" id="username_input" name="username" placeholder="Логин" required autofocus>
            <input class="form-control rounded" type="password" id="password_input" name="password" placeholder="Пароль" required>
        </div>
        <div class="rounded-group" role="group">
            <input class="btn btn-primary btn-lg" id="done" disabled style="width: 50%" type="submit" value="Войти">
            <a class="btn btn-secondary btn-lg" href="{{ url_for('web.home') }}" style="width: 50%">Позже</a>
        </div>
        <p class="text-center mt-3 text-muted">Ещё нет аккаунта? <a class="text text-lg" href="{{url_for('web.register')}}">Зарегистрируйтесь</a></p>
    </form>
{% endblock %}

scheduler/templates/settings.html
{% extends 'default_layout.html' %}
{% block head %}
    {{super()}}
    <script>
        $(function(){
            $('#username_input').keyup(function(){
                $('#login_done').attr('disabled', !usernameChecker());
            })

            $('#auth_password , #input_password, #input_confirm_password').keyup(function(){
                $('#password_done').attr('disabled', !passwordChecker());
            })

            $('#login_done').click(function(){
                var username = $('#username_input').val();
                if (usernameChecker()){
                    $.ajax({
                        url:'{{url_for('api.manage_single_user', username=user['username'])}}',
                        method:"PATCH",
                        data :{username: username}
                    }).done(function(result){
                        console.log(result)
                    })
                } else {
                    $('#login_done').attr('disabled', !usernameChecker());
                }
            })
            $('#password_done').click(function(){
                var auth_password = $('#auth_password').val();
                var password = $('#input_new_password').val();
                var confirmpassword = $('#input_new_password').val();
                if (passwordChecker()){
                    console.log(auth_password+" "+password)
                    $.ajax({
                        url:'{{url_for('api.manage_single_user', username=user['username'])}}',
                        method:"PATCH",
                        data : {auth_password: auth_password, password: password}
                    }).done(function(result){
                        console.log(result)
                    }).fail(function(){
                        $('#auth_password').addClass('is-invalid').removeClass('is-valid')
                    })
                } else {
                    console.log('not')
                    $('#login_done').attr('disabled', !usernameChecker());
                }
            })
            function usernameChecker(){
                var username = $('#username_input').val();
                console.log(username)
                $('#username-feedback').detach();
                if (username.length < 1){
                    $('#username_input').addClass('is-invalid').removeClass('is-valid');
                    return false
                }
                if (/[^A-Za-z0-9_\.]+/.test(username)){
                    $('#username_input').addClass('is-invalid').removeClass('is-valid');
                    $('#username-feedback')
                        .attr('hidden', false)
                        .append('<div class="rounded alert alert-danger alert-username">Разрешены лишь символы латиницы (a-z), арабские цифры (0-9), "_" и "."</div>');
                    return false
                }
                if (/.*(_{2}|\.{2})/.test(username)){
                    $('#username_input').addClass('is-invalid').removeClass('is-valid');
                    $('#username-feedback')
                        .attr('hidden', false)
                        .append('<div class="rounded alert alert-danger alert-username">Между двумя символами "_" или "." должна быть хотябы одна буква или цифра</div>');
                    return false
                }
                $('#username_input').addClass('is-valid').removeClass('is-invalid');
                return true;
            };
            function passwordChecker(){
                var auth_password = $('#auth_password').val();
                var password = $('#input_new_password').val();
                var confirm_password = $('#input_confirm_password').val();
                if (auth_password.length < 1){
                    $('#auth_password').addClass('is-invalid').removeClass('is-valid')
                    return false;
                }
                $('#auth_password').addClass('is-valid').removeClass('is-invalid')

                if (password.length < 1){
                    $('#input_new_password').addClass('is-invalid').removeClass('is-valid')
                    return false;
                }
                $('#input_new_password').addClass('is-valid').removeClass('is-invalid')

                if (confirm_password.length < 0 || confirm_password != password){
                    $('#input_confirm_password').addClass('is-invalid').removeClass('is-valid')
                    return false;
                }
                $('#input_confirm_password').addClass('is-valid').removeClass('is-invalid')

                return true;
            }
        })
    </script>
{% endblock head %}
{% block content %}
<div class="border rounded shadow-sm">
    <div class="accordion" id="settings_list">
        <div class="border-bottom h5 p-3">Настройки</div>
        <div class="my-2">
            <div class="px-3" data-toggle="collapse" data-target="#username_collapse" id="username_section">
                Смена логина
            </div>
            <div class="collapse px-3" id="username_collapse" data-parent="#settings_list">
                <div class="input-group input-group-sm mb-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text rounded-left">Новый логин</span>
                    </div>
                    <input class="form-control rounded-right" name="username" id="username_input" type="text">
                    <div class="invalid-feedback" id="username-feedback"></div>
                </div>
                <button class="rounded btn btn-primary btn-sm" id="login_done" disabled>Применить</button>
            </div>
            <div class="border-top my-2"></div>
            <div class="px-3 bold" data-toggle="collapse" data-target="#password_collapse" id="password_section">
                Смена пароля
            </div>
            <div class="collapse px-3" id="password_collapse" data-parent="#settings_list">
                <div class="input-group input-group-sm mb-2 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text rounded-left">Старый пароль</span>
                    </div>
                    <input class="form-control rounded-right" name="auth_password" id="auth_password" type="password">
                    <div class="invalid-feedback" id="auth-password-feedback"></div>
                </div>
                <div class="input-group input-group-sm mb-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text rounded-left">Новый пароль</span>
                    </div>
                    <input class="form-control rounded-right" name="new_password" id="input_new_password" type="password">
                    <div class="invalid-feedback" id="new-password-feedback"></div>
                </div>
                <div class="input-group input-group-sm mb-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text rounded-left">Подтверждение пароля</span>
                    </div>
                    <input class="form-control rounded-right" name="new_password" id="input_confirm_password" type="password">
                    <div class="invalid-feedback" id="confirm-password-feedback"></div>
                </div>
                <div class="rounded btn btn-primary btn-sm " disabled id="password_done">Применить</div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}